version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./codes/:/var/www/:rw
            - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./log/nginx/:/var/log/nginx:rw
        links:
            - php72:fpm
        networks:
            - frontend
            - backend

    php72:
        build: ./images/php/
        expose:
            - "9000"
        volumes:
            - ./codes/:/var/www/:rw
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini:rw
            - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
            - ./log/php-fpm/:/var/log/php-fpm/:rw
        links:
            - mysql:mysql
            - redis:redis
        networks:
            - backend
            
    mysql:
        build: 
            context: ./images/mysql
            args:
                - MYSQL_VERSION=latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=lnmp
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=123456
            - MYSQL_ROOT_PASSWORD=123456
            - TZ=UTC
        volumes:
            - ./mysql:/var/lib/mysql
            - ./log/mysql:/var/log/mysql

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
