version: '2'

services:

    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
            - "4443:443"
        volumes:
            - ./www/:/var/www/html/:rw
            - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./log/nginx/:/var/log/nginx:rw
        links:
            - php72:fpm
            
    php72:
        build: ./php/
        expose:
            - "9000"
        volumes:
            - ./www/:/var/www/html/:rw
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini:rw
            - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
            - ./log/php-fpm/:/var/log/php-fpm/:rw
        links:
            - mysql:mysql
            - redis:redis
            
    mysql:
        image: mysql:latest
        ports:
            - "33060:3306"
        volumes:
            - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - ./mysql/:/var/lib/mysql/:rw
            - ./log/mysql/:/var/log/mysql/:rw
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATEBASE: lnmp
        command: mkdir /var/lib/mysql-files
    redis:
        image: redis:latest
        ports:
            - "6379:6379"