version: '3'

networks:
  backend:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - ./codes/:/var/www/:rw
            - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./log/nginx/:/var/log/nginx:rw
        links:
            - php:fpm
        networks:
            backend: 
                aliases:
                    - image.ucie.local
                    - card.rocketbird.local
                    - yaf.local
                    - codebase.rocketbird.local
                    - staff-zt.rocketbird.local 

    php:
        build: 
            context: ./images/php/
            args:
                - VERSION=${PHP_VERSION}
                - SWOOLE_INSTALL=${SWOOLE_INSTALL}
                
        container_name: php-fpm
        expose:
            - "9000"
        restart: always
        volumes:
            - ./codes/:/var/www/:rw
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini:rw
            - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
            - ./log/php-fpm/:/var/log/php-fpm/:rw
        networks:
            - backend
            
    app:
        build:
            context: ./images/app/
            args:
                - PHP_CLI_VERSION=${PHP_CLI_VERSION}
                - NPM_INSTALL=${NPM_INSTALL}
        container_name: app
        restart: always
        volumes: 
            - ./codes/:/var/www:rw
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini:rw
            - ./conf/supervisor/:/etc/supervisor/supervisord.d/:rw
            - ./log/supervisor/:/var/log/supervisor/
            - ./log/crontab/:/var/log/crontab/
        networks:
            - backend
    npm:
        # image: node:latest
        build:
           context: ./images/npm
        container_name: npm
        ports:
            - "8888:8888" 
        volumes:
            - ./codes/:/var/www:rw
        command: "npm start"
        networks:
            - backend 
    mysql:
        build:
            context: ./images/mysql
            args:
                - VERSION=${MYSQL_VERSION}
        container_name: mysql
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_DATABASE=lnmp
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=123456
            - MYSQL_ROOT_PASSWORD=123456
            - TZ=UTC
        volumes:
            - ./mysql:/var/lib/mysql
            - ./log/mysql:/var/log/mysql
        networks:
           - backend

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - backend
           
