version: '3'

networks:
  frontend:
  backend:
  elk-filebeat:
        external: true

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - ./codes/:/var/www/:rw
            - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./log/nginx/:/var/log/nginx:rw
        links:
            - php72:fpm
        networks:
            - frontend
            - backend

    php72:
        build: 
            context: ./images/php/
            args:
                - VERSION=${PHP_VERSION}
                - SWOOLE_INSTALL=${SWOOLE_INSTALL}
                - NPM_INSTALL=${NPM_INSTALL}
                - SUPERVISOR_INSTALL=${SUPERVISOR_INSTALL}
        container_name: php-fpm
        expose:
            - "9000"
        restart: always
        volumes:
            - ./codes/:/var/www/:rw
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini:rw
            - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
            - ./conf/supervisor/:/etc/supervisor/supervisord.d/
            - ./log/php-fpm/:/var/log/php-fpm/:rw
        command: 
            - supervisor reread
            - supervisor update
            - supervisor start all
        links:
            - mysql:mysql
            - redis:redis
        networks:
            - backend

    mysql:
        build:
            context: ./images/mysql
            args:
                - VERSION=${MYSQL_VERSION}
        container_name: mysql
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_DATABASE=lnmp
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=123456
            - MYSQL_ROOT_PASSWORD=123456
            - TZ=UTC
        volumes:
            - ./mysql:/var/lib/mysql
            - ./log/mysql:/var/log/mysql
        networks:
           - backend

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - backend
    filebeat:
        image: prima/filebeat
        hostname: filebeat
        container_name: filebeat
        volumes:
            - ./conf/filebeat/conf/filebeat.yml:/filebeat.yml:rw
            - ./conf/filebeat/registry:/etc/registry:rw
            - ./conf/filebeat/module.d/:/module/:rw
            - ./log/:/var/log/system/:rw
            - ./log/filebeat:/data/logs:rw
            - ./codes/ucie-app/storage/logs/:/var/log/ucie-app/:rw
        external_links:
            - logstash
        networks:
           - elk-filebeat
